global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attachez ces étiquettes à toute série chronologique ou alerte lors de la communication avec
  # les systèmes externes (fédération, stockage distant, Alertmanager).

  external_labels:
    monitor: 'docker-host-alpha'

# Chargez et évaluez les règles de ce fichier toutes les secondes 'evaluation_interval'.

rule_files:
  - "alert.rules"

# Une configuration de scrape contenant exactement un point de terminaison à scraper.

scrape_configs:

#local instances si nous voulons monitorer l'instance de prometheus

#vps aplus instances

  - job_name: 'aplus_ent_nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['18.117.179.158:7770']

  - job_name: 'aplus_entcadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['18.117.179.158:7771']

  - job_name: 'aplus_mooc_grader'
    metrics_path: /metrics
    static_configs:
      - targets: ['18.117.179.158:8080']

  - job_name: 'aplus_frontend'
    metrics_path: /metrics
    basic_auth:
      username: 'm3tr1cs-Us3R'
      password: 'm3tr1cs-P4ssw0rD'
    static_configs:
      - targets: ['18.117.179.158:8000']

  - job_name: 'aplus_mooc_jutut'
    metrics_path: /metrics
    static_configs:
      - targets: ['18.117.179.158:8080']

  - job_name: 'aplus_acos'
    metrics_path: /metrics
    static_configs:
      - targets: ['18.117.179.158:3000']

  - job_name: 'aplus_radar'
    metrics_path: /metrics
    static_configs:
      - targets: ['18.117.179.158:8001']

  - job_name: 'aplus_rubyric_db'
    scrape_interval: 10s
    static_configs:
      - targets: ['18.117.179.158:7772']

# Alerte  Manager

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - 'alertmanager:9093'

