version: '3'

services:

  nodeexporter:
    image: prom/node-exporter:v1.7.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring_network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    restart: unless-stopped
    expose:
      - 9187
    environment:
      - DATA_SOURCE_NAME=postgresql://rubyric:rubyric@18.117.179.158:5432/rubyric?sslmode=disable
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring_network

  proxy:
    image: nginx
    container_name: proxy
    ports:
      - "7770:7770"
      - "7771:7771"
      - "7772:7772"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring_network

volumes:
  pgdata:

networks:
  monitoring_network:
    driver: bridge

