version: '3'

services:

  nodeexporter:
    image: prom/node-exporter:v1.7.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "7770:9100"
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring_network

#  postgresql:
#    image: postgres:latest
#    container_name: postgresql
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: rubyric
#      POSTGRES_PASSWORD: rubyric
#      POSTGRES_DB: rubyric
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    networks:
#      - monitoring_network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    restart: unless-stopped
    ports:
      - "7772:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://rubyric:rubyric@3.21.240.147:5432/rubyric?sslmode=disable
#    depends_on:
#      - postgresql
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    ports:
      - "7771:8080"
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - monitoring_network

volumes:
  pgdata:


networks:
  monitoring_network:
    driver: bridge
