events {}

http {
    upstream nodeexporter {
        server nodeexporter:9100;
    }

    upstream cadvisor {
        server cadvisor:8080;
    }

    upstream postgresexporter {
        server postgres-exporter:9187;
    }

    server {
        listen 7770;
        location / {
            auth_basic "Restricted Access";
            auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://nodeexporter;
        }
    }

    server {
        listen 7771;
        location / {
            auth_basic "Restricted Access";
            auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://cadvisor;
        }
    }

    server {
        listen 7772;
        location / {
            auth_basic "Restricted Access";
            auth_basic_user_file /etc/nginx/.htpasswd;
            proxy_pass http://postgresexporter;
        }
    }
}

